config/routes.rb
HelmySkrip::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}, :path => 'membership'
  resources :reports
  resources :transactions
  resources :administration_fees , :only => [:index]

  resources :products do
    member do
      get :upgrade
      post :upgrade, :action => :do_upgrade
    end
  end

  resources :nasabahs do
    member do
      put :approve
    end
  end
  resource :user, :only => [:edit, :show] , :as => :profile , :path => 'profile' do
    member do
      get '/' , :action => :profile
      get :edit, :action => :edit_profile
      put '/' , :action => :update_profile
      get :edit_password
      put :edit_password, :action => :update_password
    end
  end
  resources :users
  get 'index' => 'internal#index'
  root :to => 'internal#index'
end

app/models/nasabah.rb
class Nasabah < ActiveRecord::Base
	GENDERS 			= %w{pria perempuan}
	ID_TYPES 			= %w{KTP SIM PASPOR}
	RELIGIONS 		= %w{islam kriten katolik hindu budha other}
	NATIONALITIES = ['indonesia', 'united state', 'singapore', 'malaysia', 'australia', 'united kingdom']

	has_many :transactions, :dependent => :destroy
	belongs_to :product

	validates_presence_of :nama_lengkap, :product_id 
	after_create :add_admin_fee
	after_create :notify_director
	around_update :check_approval
	act_as_date_filter
	act_as_group_by_date
	def add_admin_fee
		AdministrationFee.create(:description => "Biaya Applikasi Nasabah baru No.rek #{self.account_number}", :amount => 50000)
	end
	def notify_director
		begin
			Pusher['nasabah_channel'].trigger 'new', :message => "#{self.nama_lengkap} - #{self.account_number} butuh direview", :location => "/nasabahs/#{self.id}"
		rescue Exception => e
			Rails.logger.error "#{'*'*30}\n#{e.message}\n#{'*'*30}"
		end
	end
	def check_approval
		before = Nasabah.find(self.id).approved?
		yield
		after = Nasabah.find(self.id).approved?
		if before == false and after == true
			after_approve
		end
	end
	
	def after_approve
		add_first_product_credit
	end

	def add_first_product_credit
		Transaction.create(:nasabah_id => self.id, :credit => self.product.month_credit)
	end
	
	def account_number
		num =  "%010d" % self.id
		num.split(//).each_slice(3).to_a.map{|r| r.join('')}.join('-')
	end
	def saldo
		transactions.sum(:credit)
	end
	def reviewed?
		['yes', 'no'].include?(self.approved)
	end
	def unreviewed?
		reviewed? == false
	end
	def approved?
		self.approved == 'yes'
	end

	def completeness_product
		@completeness_product ||= {
			:percent => '%.2f' % ((product_credit_counter*100).to_f/product.months_period.to_f) , 
			:left => product.months_period - product_credit_counter }
	end
	def product_credit_counter
		@product_credit_counter ||= transactions.where(:product_id => self.product_id).count
	end
	def self.rickshaw(params)
		q = Nasabah
			.filterize(params)
			.group_by_date.count
		res = []
		q.each{|k, v|
			res << {:x => k.to_time(:local).to_js_timestamp, :y => v}
		}
		res.sort_by {|k| k[:x] }
	end
end

app/controllers/nasabahs_controller.rb
class NasabahsController < InternalController
  before_filter :set_nasabah, only: [:show, :edit, :update, :destroy, :approve]

  # GET /nasabahs
  # GET /nasabahs.json
  def index
    respond_to do |format|    
      format.html{ @nasabahs = Nasabah.filterize(filter_params).latest.paginate(paginate_options)}      
      format.csv do
        @nasabahs = Nasabah.filterize(filter_params).latest.latest
        response.headers['Content-Disposition'] = 'attachment; filename="' + "Nasabah #{filter_params[:from].to_date.strftime("%-d %B, %Y")} - #{filter_params[:to].to_date.strftime("%-d %B, %Y")} #{Time.now.to_i}" + '.csv"'
      end      
    end
  end

  # GET /nasabahs/1
  # GET /nasabahs/1.json
  def show
  end

  # GET /nasabahs/new
  def new
    @nasabah = Nasabah.new
  end

  # GET /nasabahs/1/edit
  def edit
  end

  # POST /nasabahs
  # POST /nasabahs.json
  def create
    @nasabah = Nasabah.new(nasabah_params)

    respond_to do |format|
      if @nasabah.save
        format.html { redirect_to @nasabah, notice: 'Nasabah was successfully created.' }
        format.json { render action: 'show', status: :created, location: @nasabah }
      else
        format.html { render action: 'new' }
        format.json { render json: @nasabah.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nasabahs/1
  # PATCH/PUT /nasabahs/1.json
  def update
    respond_to do |format|
      if @nasabah.update_attributes(nasabah_params)
        format.html { redirect_to @nasabah, notice: 'Nasabah was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nasabah.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nasabahs/1
  # DELETE /nasabahs/1.json
  def destroy
    @nasabah.destroy
    respond_to do |format|
      format.html { flash[:notice] = "Successfully destroy #{@nasabah.nama_lengkap} | #{@nasabah.account_number}" ; redirect_to nasabahs_url }
      format.json { head :no_content }
    end
  end

  def approve
    @nasabah.update_attribute(:approved, params[:approve].blank? ? 'yes' :  'no' ) if params[:approve].blank? or params[:approve] == 'no'
    respond_to do |format|
      format.html { redirect_to nasabahs_url }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nasabah
      @nasabah = Nasabah.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nasabah_params
      params.require(:nasabah).permit(:nama_lengkap , :tempa, :tanggal_lahir , :jenis_kelamin , :kewarganegaraan , :no_identitas, :type_identitas, :expire_identitas, :no_npwp , :alamat_rumah, :alamat_surat, :no_tlp_kantor, :no_ponsel , :no_faximile , :email , :rekening_koran_gabungan , :status_pernikahan , :status_rumah_tinggal, :tanggal_rumah_tinggal, :no_tlp_rumah , :pekerjaan_utama, :pendapatan_bulanan , :bidang_usaha , :sumber_dana , :tujuan_penggunaan_dana , :tujuan_penggunaan_rekening , :nama_ibu_kandung , :agama, :product_id)
    end
end

app/helpers/nasabahs_helper.rb
module NasabahsHelper
end

app/views/nasabahs/_form.html.haml
= form_for @nasabah , :html => {autocomplete: "off"} do |f|
	- if @nasabah.errors.any?
		#error_explanation
			%h2= "#{pluralize(@nasabah.errors.count, "error")} prohibited this nasabah from being saved:"
			%ul
				- @nasabah.errors.full_messages.each do |msg|
					%li= msg
					
	.form-horizontal
		%h4.no-bold Pilih Product
		%hr.top-off
		.control-group
			=f.label :product_id, :class => 'control-label'
			.controls
				=f.select :product_id, ['', '']+Product.collection_selects,{} , :class => '', 'data-placeholder' => 'Choose one'
		
		%hr.top-off
		%h4.no-bold Data Pribadi
		%hr.top-off

		.control-group
			=f.label :nama_lengkap, :class => 'control-label'
			.controls
				=f.text_field :nama_lengkap, :class => 'span8'

		.control-group
			=f.label :status_pernikahan, :class => 'control-label'
			.controls
				.form-inline
					-for gender in ['sudah_nikah', 'belum_menikah']
						%label.radio{:style => 'margin-right: 10px;'}
							=f.radio_button :status_pernikahan, gender
							=gender.titleize


		.control-group
			=f.label :tanggal_lahir, :class => 'control-label'
			.controls
				#nasabah-tgl-lahir.input-append
					=f.text_field :tanggal_lahir, :data => {:format => 'yyyy-MM-dd'}
					%span.add-on
						%i.icon.icon-calendar
				=content_for(:bottom_js) do 
					:javascript						
						$(function() {
							$('#nasabah-tgl-lahir').datetimepicker({
								pickTime: false
							});
						})
		.control-group
			=f.label :jenis_kelamin, :class => 'control-label'
			.controls
				.form-inline
					-for gender in Nasabah::GENDERS
						%label.radio{:style => 'margin-right: 10px;'}
							=f.radio_button :jenis_kelamin, gender
							=gender.titleize

		.control-group
			=f.label :kewarganegaraan, :class => 'control-label'
			.controls
				=f.select :kewarganegaraan, ['', '']+Nasabah::NATIONALITIES.map{|i|[i.titleize, i]},{} , :class => 'chzn-select', 'data-placeholder' => 'Choose one'

		.control-group
			=f.label :no_identitas, :class => 'control-label'
			.controls
				=f.text_field :no_identitas, :class => 'span8'

		.control-group
			=f.label :type_identitas, :class => 'control-label'
			.controls
				.form-inline
					-for gender in Nasabah::ID_TYPES
						%label.radio{:style => 'margin-right: 10px;'}
							=f.radio_button :type_identitas, gender
							=gender.upcase
		.control-group
			=f.label :expire_identitas, :class => 'control-label'
			.controls
				#nasabah-expire_identitas.input-append
					=f.text_field :expire_identitas, :data => {:format => 'yyyy-MM-dd'}
					%span.add-on
						%i.icon.icon-calendar
				=content_for(:bottom_js) do 
					:javascript						
						$(function() {
							$('#nasabah-expire_identitas').datetimepicker({
								pickTime: false
							});
						})				
		.control-group
			=f.label :alamat_rumah, :class => 'control-label'
			.controls
				=f.text_field :alamat_rumah, :class => 'span8'

		.control-group
			=f.label :alamat_surat, :class => 'control-label'
			.controls
				=f.text_field :alamat_surat, :class => 'span8'
		.control-group
			=f.label :email, :class => 'control-label'
			.controls
				=f.text_field :email, :class => 'span8'

		.control-group
			=f.label :no_ponsel, :class => 'control-label'
			.controls
				=f.text_field :no_ponsel, :class => 'span8'


		%hr.bottom-off
		%h4.no-bold Data Pekerjaan
		%hr.top-off
		.control-group
			=f.label :pekerjaan_utama, :class => 'control-label'
			.controls
				=f.text_field :pekerjaan_utama, :class => 'span8'

		.control-group
			=f.label :pendapatan_bulanan, :class => 'control-label'
			.controls
				=f.text_field :pendapatan_bulanan, :class => 'span8'

		.control-group
			=f.label :bidang_usaha, :class => 'control-label'
			.controls
				=f.text_field :bidang_usaha, :class => 'span8'

		.control-group
			=f.label :no_tlp_kantor, :class => 'control-label'
			.controls
				=f.text_field :no_tlp_kantor, :class => 'span8'

		.control-group
			=f.label :no_npwp, :class => 'control-label'
			.controls
				=f.text_field :no_npwp, :class => 'span8'

		.control-group
			=f.label :no_faximile, :class => 'control-label'
			.controls
				=f.text_field :no_faximile, :class => 'span8'

		%hr.bottom-off
		%h4.no-bold Data Pelengkap
		%hr.top-off

		.control-group
			=f.label :rekening_koran_gabungan, :class => 'control-label'
			.controls
				=f.text_field :rekening_koran_gabungan, :class => 'span8'

		.control-group
			=f.label :status_rumah_tinggal, :class => 'control-label'
			.controls
				=f.text_field :status_rumah_tinggal, :class => 'span8'

		.control-group
			=f.label :tanggal_rumah_tinggal, :class => 'control-label'
			.controls
				=f.text_field :tanggal_rumah_tinggal, :class => 'span8'

		.control-group
			=f.label :no_tlp_rumah, :class => 'control-label'
			.controls
				=f.text_field :no_tlp_rumah, :class => 'span8'

		.control-group
			=f.label :sumber_dana, :class => 'control-label'
			.controls
				=f.text_field :sumber_dana, :class => 'span8'

		.control-group
			=f.label :tujuan_penggunaan_dana, :class => 'control-label'
			.controls
				=f.text_field :tujuan_penggunaan_dana, :class => 'span8'

		.control-group
			=f.label :tujuan_penggunaan_rekening, :class => 'control-label'
			.controls
				=f.text_field :tujuan_penggunaan_rekening, :class => 'span8'

		.control-group
			=f.label :nama_ibu_kandung, :class => 'control-label'
			.controls
				=f.text_field :nama_ibu_kandung, :class => 'span8'

		.control-group
			=f.label :agama, :class => 'control-label'
			.controls
				=f.select :agama, ['', '']+Nasabah::RELIGIONS.map{|i|[i.titleize, i]},{} , :class => 'chzn-select', 'data-placeholder' => 'Choose one'



		.form-actions
			= f.submit 'Save', :class => 'btn'

app/views/nasabahs/edit.html.haml
.component-heading
	%h3.no-bold
		%i.icon.icon-group
		Edit Nasabah


= render 'form'

app/views/nasabahs/index.csv.haml
Nasabah #{@filter_params[:from].to_date.strftime("%d/%m/%Y")} - #{@filter_params[:to].to_date.strftime("%-d/%m/%Y")}


Nama, No. Rek, Product, Saldo
-for ns in @nasabahs
	="#{ns.nama_lengkap}, #{ns.account_number}, #{ns.product.name_version}, #{ns.saldo}"

app/views/nasabahs/index.html.haml
.component-heading
	.row-fluid
		.span8
			%h3.no-bold
				%i.icon.icon-group
				Data Nasabah
		.span4
			.pull-right
				.btn-group
					=link_to '<i class="icon icon-plus-sign"></i> Nasabah Baru'.html_safe, new_nasabah_path, :class => 'btn-mini btn btn-primary'
					= link_to '<i class="icon icon-download"></i> Download Excel'.html_safe, url_for(params.merge(:format => :csv)), :class => 'btn btn-mini'
					= link_to '<i class="icon icon-print"></i> Print'.html_safe, '#', :class => 'btn btn-mini', :onclick=> "window.print()"


=render 'filter'
%table.table.table-condensed.table-stripped
	%tr
		%th Nama
		%th No. Rek
		%th Product
		%th Saldo
		%th
			.center-text Product Completeness
		%th.dont-print
			.center-text Action

	- @nasabahs.each do |nasabah|

		%tr
			%td=link_to nasabah.nama_lengkap, nasabah
			%td=nasabah.account_number
			%td=nasabah.product.name_version
			%td=money_formater nasabah.saldo
			%td.dont-print
				.center-text
					.btn-group
						%span.btn.btn-mini.btn-success.disabled="#{nasabah.completeness_product[:percent]} %"
						%span.btn.btn-mini.btn-info.disabled="#{nasabah.completeness_product[:left]} left"					
			%td
				.btn-toolbar{:style => 'margin: 0px;'}
					.btn-group
						-if can?(:update, nasabah)
							= link_to '<i class="icon icon-pencil"></i>'.html_safe, edit_nasabah_path(nasabah), :class => 'btn btn-mini'
						-if can?(:destroy, nasabah)
							= link_to '<i class="icon icon-remove"></i>'.html_safe, nasabah_path(nasabah), :class => 'btn btn-mini',:method => :delete, :data => { :confirm => 'Are you sure?' }
					-if nasabah.unreviewed? and can?(:approve, nasabah)	
						.btn-group
							= link_to '<i class="icon icon-ok-sign"></i> Approve'.html_safe, approve_nasabah_path(nasabah), :class => 'btn btn-mini btn-success', :title => 'Approve', :method => :put
							= link_to '<i class="icon icon-ban-circle"></i> Disapprove'.html_safe, approve_nasabah_path(nasabah, :approve => 'no'), :class => 'btn btn-mini btn-danger btn-danger', :title => 'Approve', :method => :put
.pagination
	= will_paginate @nasabahs
	.page_info
		= page_entries_info @nasabahs

				

app/views/nasabahs/new.html.haml
.component-heading
	%h3.no-bold
		%i.icon.icon-group
		Nasabah Baru


= render 'form'

= link_to 'Back', nasabahs_path

app/views/nasabahs/show.html.haml
.component-heading
	.row-fluid
		.span6
			%small Data Nasabah
			%h3.no-bold
				%i.icon.icon-group
				%b=@nasabah.nama_lengkap
				%small=@nasabah.account_number

		.span6
			.pull-right
				.btn-toolbar
					.btn-group

						= link_to '<i class="icon icon-pencil"></i> Edit'.html_safe, edit_nasabah_path(@nasabah), :class => 'btn btn-small'
						= link_to '<i class="icon icon-arrow-left"></i> Back'.html_safe, nasabahs_path, :class => 'btn btn-small'
						= link_to '<i class="icon icon-print"></i> Print'.html_safe, '#', :class => 'btn btn-small', :onclick=> "window.print()"
					-if @nasabah.unreviewed? and can?(:approve, @nasabah)				
						.btn-group
							= link_to '<i class="icon icon-ok-sign"></i> Approve'.html_safe, approve_nasabah_path(@nasabah), :class => 'btn btn-small btn-success', :title => 'Approve', :method => :put
							= link_to '<i class="icon icon-ok-sign"></i> Disapprove'.html_safe, approve_nasabah_path(@nasabah, :approve => 'no'), :class => 'btn btn-small btn-danger btn-danger', :title => 'Approve', :method => :put

.row-fluid
	.span8

		%table.table-condensed.table-stripped.table
			%tbody
				%tr
					%td{:colspan => '2'}
						%h4 Data Pribadi
				%tr
					%td.span3
						%b Status Pernikahan
					%td.span9=@nasabah.status_pernikahan.titleize
				%tr
					%td.span3
						%b Tanggal lahir
					%td.span9=@nasabah.tanggal_lahir
				%tr
					%td.span3
						%b Kewarganegaraan
					%td.span9=@nasabah.kewarganegaraan.titleize
				%tr
					%td.span3
						%b No Identitas
					%td.span9="#{@nasabah.no_identitas}(#{@nasabah.type_identitas}) - sampai #{@nasabah.expire_identitas}"
				%tr
					%td.span3
						%b Alamat Rumah
					%td.span9=@nasabah.alamat_rumah
				%tr
					%td.span3
						%b Alamat Surat
					%td.span9=@nasabah.alamat_surat
				%tr
					%td.span3
						%b Email
					%td.span9=@nasabah.email
				%tr
					%td.span3
						%b No. Ponsel
					%td.span9=@nasabah.no_ponsel
				%tr
					%td{:colspan => 2}
						%h4 Data Pekerjaan
				%tr
					%td.span3
						%b Pekerjaan utama
					%td.span9=@nasabah.pekerjaan_utama
				%tr
					%td.span3
						%b Pendapatan Bulanan
					%td.span9=@nasabah.pendapatan_bulanan
				%tr
					%td.span3
						%b Bidang usaha
					%td.span9=@nasabah.bidang_usaha
				%tr
					%td.span3
						%b No. Tlp Kantor
					%td.span9=@nasabah.no_tlp_kantor
				%tr
					%td.span3
						%b No. NPWP
					%td.span9=@nasabah.no_npwp
				%tr
					%td.span3
						%b No. Faximile
					%td.span9=@nasabah.no_faximile
				%tr
					%td{:colspan => 2}
						%h4 Data Pelengkap

				%tr
					%td.span3
						%b Rek. Koran Gabungan
					%td.span9=@nasabah.rekening_koran_gabungan
				%tr
					%td.span3
						%b Status rumah tinggal
					%td.span9=@nasabah.status_rumah_tinggal
				%tr
					%td.span3
						%b Tanggal rumah tinggal
					%td.span9=@nasabah.tanggal_rumah_tinggal
				%tr
					%td.span3
						%b No Tel rumah
					%td.span9=@nasabah.no_tlp_rumah
				%tr
					%td.span3
						%b Sumber dana
					%td.span9=@nasabah.sumber_dana
				%tr
					%td.span3
						%b Tujuan penggunaan dana
					%td.span9=@nasabah.tujuan_penggunaan_dana
				%tr
					%td.span3
						%b Tujuan penggunaan rekening
					%td.span9=@nasabah.tujuan_penggunaan_rekening
				%tr
					%td.span3
						%b Nama Ibu Kandung
					%td.span9=@nasabah.nama_ibu_kandung
				%tr
					%td.span3
						%b Agama
					%td.span9=@nasabah.agama
	.span4
		%span Jenis Produk
		%h3{:style => 'margin-top: 0px'}=@nasabah.product.name_version
		%hr.both-off
		/ .center-text
		%small Completeness
		%br
		.btn-group
			%span.btn.btn-large.btn-success.disabled.span6="#{@nasabah.completeness_product[:percent]} %"
			%span.btn.btn-large.btn-info.disabled.span6="#{@nasabah.completeness_product[:left]} left"		
		%hr
		/ .center-text
		%small Saldo
		%br
		%h2=money_formater @nasabah.saldo