config/routes.rb
HelmySkrip::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}, :path => 'membership'
  resources :reports
  resources :transactions
  resources :administration_fees , :only => [:index]

  resources :products do
    member do
      get :upgrade
      post :upgrade, :action => :do_upgrade
    end
  end

  resources :nasabahs do
    member do
      put :approve
    end
  end
  resource :user, :only => [:edit, :show] , :as => :profile , :path => 'profile' do
    member do
      get '/' , :action => :profile
      get :edit, :action => :edit_profile
      put '/' , :action => :update_profile
      get :edit_password
      put :edit_password, :action => :update_password
    end
  end
  resources :users
  get 'index' => 'internal#index'
  root :to => 'internal#index'
end

app/controllers/internal_controller.rb
class InternalController < ApplicationController
	before_filter :authenticate_user!
  # load_resource
  authorize_resource

	skip_load_resource :only => :index
	skip_authorize_resource :only => :index

  rescue_from CanCan::AccessDenied do |exception|
  	respond_to do |wants|
  		wants.html { redirect_to root_path, :alert => exception.message }
  	end
  end
	
	def index
	end

  def current_ability
    @current_ability ||= Ability.new(current_user || User.new)
  end	

end

app/views/internal/_filter.html.haml
.row-fluid
	.span4
		%p
			%i.icon.icon-calendar
			=@filter_params[:from].to_date.strftime("%-d %B, %Y")
			%i.icon.icon-double-angle-right
			=@filter_params[:to].to_date.strftime("%-d %B, %Y")
	.span8
		.pull-right
			.btn-group
				-time = Time.now
				%a.btn.btn-mini.btn-info{:href => url_for(:filter => {:from => time.beginning_of_day.strftime("%-d %B, %Y") , :to => time.end_of_day.strftime("%-d %B, %Y") })} Daily
				%a.btn.btn-mini.btn-info{:href => url_for(:filter => {:from => time.beginning_of_week.strftime("%-d %B, %Y") , :to => time.end_of_week.strftime("%-d %B, %Y") })} Weekly
				%a.btn.btn-mini.btn-info{:href => url_for(:filter => {:from => time.beginning_of_month.strftime("%-d %B, %Y") , :to => time.end_of_month.strftime("%-d %B, %Y") })} Monthly												
				%span#show-filter.btn.btn-mini.btn-primary{:role =>"button", :data => {:toggle => 'modal', :target => '#filter-modal', :backdrop => 'false'}}
					%i.icon.icon-filter
					Adnvance Filter
				-if params[:filter]
					=link_to '<i class="icon icon-remove-sign"></i> Reset Filter'.html_safe, url_for(:action => :index), :class => 'btn btn-mini btn-warning'
- filter_params = params[:filter] || {}
.modal.hide.fade#filter-modal{:role => 'dialog'}
	.modal-header
		%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
		%h3.no-bold
			%i.icon.icon-filter		
			Advance Filter
	%form{:action => url_for(:action => :index), :style => 'margin-bottom : 0px;'}
		.modal-body
			.row-fluid
				.span6
					%label Mulai Tanggal
					.bt-timepick.input-append
						%input.pickadate_target.span12{:type => :text, :name => 'filter[from]',  :value => filter_params[:to], :data => {:format => 'yyyy-MM-dd'}}					
						%span.add-on
							%i.icon.icon-calendar
				.span6
					%label Sampai Tanggal
					.bt-timepick.input-append
						%input.pickadate_target.span12{:type => :text, :name => 'filter[to]',  :value => filter_params[:to], :data => {:format => 'yyyy-MM-dd'}}					
						%span.add-on
							%i.icon.icon-calendar


		.modal-footer
			%button.btn Search	
=content_for(:bottom_js) do 
	:javascript						
		$(function() {
			$('.bt-timepick').datetimepicker({
				pickTime: false
			});
		})	

app/views/internal/_front_navigation.html.haml
.container.dont-screen
	.row-fluid
		.span1
			=image_tag('icon_brand.png')
		.span11
			%h3.no-bold
				Bank Syariah 
				%b AT-Taqwa
	%hr.bottom-off
.navbar.navbar-fixed-top#topest-bar
	.navbar
		.navbar-inner
			.container
				.logo-brand
					%a{:href => root_url}
						=image_tag('icon_brand.png')
				%a.brand{:href => root_url}
					Bank Syariah 
					%b AT-Taqwa
				.nav-collapse.collapse.navbar-responsive-collapse
					=render 'top_menu'
				%ul.nav.pull-right{:style => 'margin-right:15px'}
					-if current_user
						%li.dropdown
							%a.dropdown-toggle{:href=>"#", 'data-toggle' => "dropdown"}
								%i.icon.icon-user
								%b.caret
							%ul.dropdown-menu
								%li
									=link_to "#{current_user.name.titleize} - #{current_user.roles.first.titleize}", profile_path
								%li.divider
								%li
									=link_to '<i class="icon icon-edit"></i> Edit'.html_safe, edit_profile_path
								%li
									=link_to '<i class="icon icon-unlock"></i> Ubah Password'.html_safe, edit_password_profile_path
								-if can?(:manage, User)
									%li
										=link_to '<i class="icon icon-th-list"></i> Admin Users'.html_safe, users_path

								%li.divider
								%li
									=link_to '<i class="icon icon-off"></i> Keluar'.html_safe, destroy_user_session_path, :method => "delete"

app/views/internal/_top_menu.html.haml
%ul.nav
	-if can?(:manage, Nasabah)
		%li{:class => params[:controller] == 'nasabahs' ? 'active' : ''}
			=link_to '<i class="icon icon-group"></i> Data Nasabah'.html_safe, nasabahs_path
	-if can?(:manage, Transaction) or can?(:manage , AdministrationFee)
		%li.dropdown{:class => params[:controller] =~ /transactions|administration_fees/ ? 'active' : ''}
			%a.dropdown-toggle{:href=>"#", 'data-toggle' => "dropdown"}
				%i.icon.icon-exchange 
				Transaction
				%b.caret
			%ul.dropdown-menu
				-if can?(:manage, Transaction)
					%li
						=link_to  '<i class="icon icon-th-list"></i> List Transaction'.html_safe, transactions_path
				-if can?(:manage , AdministrationFee)
					%li
						=link_to  '<i class="icon icon-money"></i> Administration Fee'.html_safe, administration_fees_path

	-if can?(:manage, Product)
		%li{:class => params[:controller] == 'products' ? 'active' : ''}
			=link_to  '<i class="icon icon-barcode"></i> Produk'.html_safe, products_path			
	-if can?(:manage, :reports)
		%li
			=link_to  '<i class="icon icon-bar-chart"></i> Report'.html_safe, reports_path