config/routes.rb
HelmySkrip::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}, :path => 'membership'
  resources :reports
  resources :transactions
  resources :administration_fees , :only => [:index]

  resources :products do
    member do
      get :upgrade
      post :upgrade, :action => :do_upgrade
    end
  end

  resources :nasabahs do
    member do
      put :approve
    end
  end
  resource :user, :only => [:edit, :show] , :as => :profile , :path => 'profile' do
    member do
      get '/' , :action => :profile
      get :edit, :action => :edit_profile
      put '/' , :action => :update_profile
      get :edit_password
      put :edit_password, :action => :update_password
    end
  end
  resources :users
  get 'index' => 'internal#index'
  root :to => 'internal#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, :code, :month_credit, :months_period, :presence => true
	validates :code, :uniqueness => {:scope => :version, :message => 'maybe you want to create other version, is it?'}

	after_initialize :assign_version, :on => :create, :if => 'new_record? and code.blank? == false'
	before_validation :assign_first_credit
	before_destroy :check_nasabah_existence
	has_many :nasabahs
	has_many :other_versions, :class_name => 'Product', :foreign_key => 'code' , :primary_key => 'code'
	def assign_first_credit
		self.first_credit = self.month_credit
	end
	def assign_version
		current_ver = Product.where(:code => self.code).count
		self.version = current_ver+1
	end

	def clone_attr_for_upgrade
		as_json(:only => [:code, :name])
	end
	def check_nasabah_existence
		if (counter = Nasabah.where(:product_id => self.id).count) > 0
			errors.add(:base, "masih ada #{counter} nasabah yang terdaftar dengan product #{self.name_version}") 
			return false
		end
		true
	end

	def transaction_context trx, state = :credit
		counter = trx.nasabah.transactions.where(:product_id => self.id).count
		month =  trx.nasabah.created_at.to_time+counter.month
		"Setoran ##{counter+1} #{self.name} V.#{self.version} - #{month.strftime('%B %Y')}"
	end

	def name_version
		"#{read_attribute(:name)} V.#{read_attribute(:version)}"
	end

	def self.collection_selects
		Product.select(:code).uniq.map do |p|
			pr = Product.where(:code => p.code).order('version desc').limit(1).first
			["#{pr.name} v.#{pr.version}", pr.id]
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < InternalController
  before_filter :set_master_product, :only => [:upgrade, :do_upgrade]
  before_filter :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def upgrade
    @product = Product.new(@master_product.clone_attr_for_upgrade)
  end

  def do_upgrade
    @product = Product.new(@master_product.clone_attr_for_upgrade.merge(product_params))
    if @product.save
      redirect_to @product, notice: 'Product was successfully upgraded.'
    else  
      flash[:alert] = @product.errors.to_a.join(', ')
      render :action => :upgrade
    end
  end
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    flash[:alert] = @product.errors.to_a.join(', ') unless @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
    def set_master_product
      set_product
      @master_product = @product
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :first_credit, :month_credit, :description, :months_period, :version, :code)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
	- if @product.errors.any?
		#error_explanation
			%h3.no-bold= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
			%ul
				- @product.errors.full_messages.each do |msg|
					%li= msg
	.form-horizontal
		.control-group
			= f.label :name, :class => 'control-label'
			.controls
				= f.text_field :name, :class => 'span8'
		.control-group
			= f.label :description, :class => 'control-label'
			.controls
				= f.text_area :description, :class => 'span8', :rows => '5'

		-if @product.nasabahs.count == 0
			.control-group
				= f.label :month_credit, :class => 'control-label'
				.controls
					= f.number_field :month_credit, :class => 'span8'	
			.control-group
				= f.label :months_period, :class => 'control-label'
				.controls
					= f.number_field :months_period, :class => 'span8'
		-if @product.other_versions.count == 1
			.control-group
				= f.label :code, :class => 'control-label'
				.controls
					= f.text_field :code, :class => 'span8'
		.form-actions
			= f.submit 'Save', :class => 'btn'

app/views/products/edit.html.haml
.component-heading
	.row-fluid
		.span8
			%small Editing Product
			%h3.no-bold
				%i.icon.icon-barcode
				=@product.name_version
		.span4
			.pull-right
				= link_to 'Back', products_path, :class => 'btn'


= render 'form'

app/views/products/index.html.haml
.component-heading
	.row-fluid
		.span8
			%h3.no-bold
				%i.icon.icon-barcode
				Products
		.span4
			.pull-right
				= link_to 'New Product', new_product_path, :class => 'btn'


%table.table.table-condensed.table-stripped
	%tr
		%th Name
		%th First credit
		%th Month credit
		%th Months period
		%th Version
		%th Produk code
		%th Action


	- @products.each do |product|
		%tr
			%td= product.name
			%td= money_formater product.first_credit
			%td= money_formater product.month_credit
			%td="#{product.months_period} (#{product.months_period/12} #{'year'.pluralize(product.months_period)})"
			%td= product.version
			%td= product.code
			%td
				.btn-group
					= link_to '<i class="icon icon-pencil"></i>'.html_safe, edit_product_path(product), :class => 'btn btn-mini btn-primary', :title => 'Edit'
					= link_to '<i class="icon icon-remove"></i>'.html_safe, product, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger', :title => 'Destroy'
					= link_to '<i class="icon icon-upload-alt"></i>'.html_safe, upgrade_product_path(product), :class => 'btn btn-mini btn-info', :title => 'Upgrade'

%br

app/views/products/new.html.haml
.component-heading
	.row-fluid
		.span8
			%h3.no-bold
				%i.icon.icon-barcode
				Products Baru
		.span4
			.pull-right
				= link_to 'Back', products_path, :class => 'btn'



= render 'form'

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b First credit:
  = @product.first_credit
%p
  %b Month credit:
  = @product.month_credit
%p
  %b Description:
  = @product.description
%p
  %b Months period:
  = @product.months_period
%p
  %b Version:
  = @product.version
%p
  %b Produk code:
  = @product.code

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

app/views/products/upgrade.html.haml
.component-heading
	.row-fluid
		.span8
			%small Ugrade #{@master_product.name} v.#{@product.version}
			%h3.no-bold
				%i.icon.icon-barcode
				=@product.name_version
		.span4
			.pull-right
				= link_to 'Back', products_path, :class => 'btn'


= form_for @product, :url => upgrade_product_path(@master_product) do |f|
	.form-horizontal
		.control-group
			= f.label :name, :class => 'control-label'
			.controls
				= f.text_field :name, :class => 'span8'
		.control-group
			= f.label :month_credit, :class => 'control-label'
			.controls
				= f.number_field :month_credit, :class => 'span8'
				%p.help-block previous version : #{money_formater @master_product.month_credit}
		.control-group
			= f.label :description, :class => 'control-label'
			.controls
				= f.text_area :description, :class => 'span8', :rows => '5'
		.control-group
			= f.label :months_period, :class => 'control-label'
			.controls
				= f.number_field :months_period, :class => 'span8'
				%p.help-block previous version : #{ @master_product.months_period}				
		.form-actions
			= f.submit 'Save', :class => 'btn'